### ISSUE TITLE
The Charts plugin does not work with admonition

### ISSUE THREAD

**Issue by WychWitch** [valentine195/obsidian-admonition#106]
Hello! I'm not sure if this is something that's possible to fix, but I've run into a strange issue.

When using the [Charts plugin](https://github.com/phibr0/obsidian-charts) whenever I try wrapping it in admonition it gives the following error:

```
Evaluation Error: SyntaxError: missing ) after argument list
    at DataviewInlineApi.eval {...}
```

Outside of admonition it works just fine, which is very strange.

I first opened an issue on the Charts plugin page [here](https://github.com/phibr0/obsidian-charts/issues/22), but the owner of the repo couldn't find any issue with my code and suggested it might be an issue with admonition instead, so here I am!

<details>
<summary> Here's my code,  of course with the encompassing admonition block</summary>

````````js

````ad-note
title: Blood Pressure Graph Sept-Oct
icon: tint
color: 220, 20, 60
collapse: closed

```dataviewjs

var dateStart = "2021-09-01";

var dateEnd = "2021-10-31";

var dnotes = dv.pages("#daily-log").where(p => 
            dv.date(p.file.name) >= 
            dv.date(dateStart) && 
            dv.date(p.file.name) <= 
            dv.date(dateEnd));

        var tdata = [];
        var bdata = [];
        var allLabels = [];
        
        for (let i = 0; i < dnotes.length; i++) {
            
            if (dnotes[i].avgbp){
                allLabels.push(dnotes[i].file.name) 
                var strNum = dnotes[i].avgbp.split("/")[0]
                var num = parseInt(strNum)
                
                tdata.push(num);
                
                var strrNum = dnotes[i].avgbp.split("/")[1]
                var numm = parseInt(strrNum)
                    bdata.push(numm);
                    //console.log(parseInt(dnotes[i].avgbp.trimLeft("/"));
                    //console.log(parseInt(dnotes[i].avgbp.trimRight("/"))
                }
            
        }
        allLabels.reverse()
        tdata.reverse()
        bdata.reverse()

        const chartData = {
            type: 'bar',
            data: {
                labels: allLabels,
                width: "10%",
                datasets: [{
                    label: 'Top',
                    data: tdata     ,
                    backgroundColor: ['rgba(217, 121, 137)'
                    ],
                }, 
                {
                    label: 'Bottom',
                    data: bdata, 
                    backgroundColor: 'rgba(121, 156, 212)'}]
            }
        }

        //console.log(allLabels)
        const average = (array) => array.reduce((a, b) => a + b) / array.length;

        if (!String.prototype.format) {
        String.prototype.format = function() {
            var args = arguments;
            return this.replace(/{(\d+)}/g, function(match, number) { 
            return typeof args[number] != 'undefined'
                ? args[number]
                : match
            ;
            });
        };
        }
        var avgBP = 'Average Blood Pressure: {0}/{1}'.format(
            Math.round(
                (average(tdata) + Number.EPSILON) * 100) / 100,
            Math.round(
                (average(bdata) + Number.EPSILON) * 100) / 100);


window.renderChart(chartData, this.container);

dv.header(2, avgBP)

```
````
`````````

</details>

<details>
<summary>Here is the full error stack, I can't make heads or tails of it sadly</summary>

```error

Evaluation Error: SyntaxError: missing ) after argument list
    at DataviewInlineApi.eval (eval at <anonymous> (app://obsidian.md/app.js:1:1215379), <anonymous>:12641:21)
    at evalInContext (eval at <anonymous> (app://obsidian.md/app.js:1:1215379), <anonymous>:12642:7)
    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1215379), <anonymous>:12653:36)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1215379), <anonymous>:26:71)
    at new Promise (<anonymous>)
    at __awaiter (eval at <anonymous> (app://obsidian.md/app.js:1:1215379), <anonymous>:22:12)
    at asyncEvalInContext (eval at <anonymous> (app://obsidian.md/app.js:1:1215379), <anonymous>:12648:12)
    at DataviewJSRenderer.eval (eval at <anonymous> (app://obsidian.md/app.js:1:1215379), <anonymous>:13175:23)
    at Generator.next (<anonymous>)

```

</details>

dataviewjs seems to work fine otherwise with admonition, as wrapping `dv.header(2, "test")` in the block works just fine. Is there something I'm doing wrong? If the bug is beyond the scope of this project, I fully understand! Thanks for making this plugin in the first place ^^

**Comment by WychWitch** [comment]
> 
> 
> And this exact chart works outside an admonition?

Yes! I double checked it, it works flawlessly until I wrap it in an admonition block. Here are some screenshots if that helps?
<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/1291820/137400654-9971387c-e78a-4b64-ae0d-84234667470d.png)

![image](https://user-images.githubusercontent.com/1291820/137400980-8450dade-6d04-46b6-a403-0b2630cfc6a5.png)


</details>

**Comment by valentine195** [comment]
Hi, is this still an issue? I just tried your code and it works.

**Comment by WychWitch** [comment]
> Hi, is this still an issue? I just tried your code and it works.

YEP!! I totally forgot about this but it totally works now!!  Idk what changed but whatever happened I'm glad ^^
